export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const GET_TODOS_INITIALIZE = "GET_TODOS_INITIALIZE";
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS";
export const COMPLETE_TODO = "COMPLETE_TODO";
