export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const GET_TODOS_INITIALIZE = "GET_TODOS_INITIALIZE";
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS";
export const FETCH_TODOS_SUCCEEDED = "FETCH_TODOS_SUCCEEDED";
export const FETCH_TODOS_FAILED = "FETCH_TODOS_FAILED";
