export const GET_TODOS_ERROR = "GET_TODOS_ERROR";
export const ADD_TODO_ERROR = 'ADD_TODO_ERROR';
export const REMOVE_TODO_ERROR = 'REMOVE_TODO_ERROR';
export const COMPLETE_TODO_ERROR = "COMPLETE_TODO_ERROR";
export const EDIT_TODO_ERROR = "EDIT_TODO_ERROR";